[project]
name = "auto-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cryptography<46",
    "gradio>=6.28.0",
    "joblib>=1.6.0",
    "lightgbm>=4.7.0",
    "matplotlib>=3.11.2",
    "mlflow>=3.16.1",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "pillow>=12.3.0",
    "plotly>=7.1.0",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "xgboost>=3.4.1",
]

[project.scripts]
auto-ml = "auto_ml:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
